spring.output.ansi.enabled: always

logging:
    level:
        root: WARN
        com.elderbyte: ${LOG_LEVEL:INFO}
        org.springframework.kafka.config: DEBUG # Display KStream Topology

kafka:
  client:
    enabled: true
    servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      transaction.id: demo-app
    consumer:
      enabled: true
      pollTimeout: 3000
    streams:
      commitInterval: 1s
      processingGuarantee: at_least_once
      replicationFactor: 1
      producerAcks: 1
      optimizeTopology: all
      stateDir: ./kstream-data
    topics:
      - name: _demo.cdc.orders.order
        partitions: 1
        cleanUpPolicy: delete
        retention: 1h
      - name: _demo.cdc.orders.item
        partitions: 1
        cleanUpPolicy: delete
        retention: 1h
      - name: demo.store.orders.order
        partitions: 1
        cleanUpPolicy: compact
        retention: 24h
